sonar.projectKey=ProyectoRestaurante
sonar.projectName=Proyecto Restaurante
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.token=squ_2dedc2d67b1dd7d0a66c3fde81946f265b00c9ac
sonar.java.binaries=.